apiVersion: v1
kind: Namespace
metadata:
  name: sttt
---
kind: Service
apiVersion: v1
metadata:
  name: sttt
  namespace: sttt
  labels:
    app: sttt
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: sttt
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10000
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sttt
  namespace: sttt
  labels:
    app: sttt
spec:
  selector:
    matchLabels:
      name: sttt
  template:
    metadata:
      labels:
        name: sttt
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: sttt
          image: reg.captainjustin.space/just1689/sttt:dev7
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: sttt
  namespace: sttt
spec:
  rules:
    - http:
        paths:
          - path: /sttt
            backend:
              serviceName: sttt
              servicePort: 8080
