{
 "title": "Tic Tac Toe",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Plays",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sttt_players_plays)" }
   ]
  },
  {
   "title": "Wins",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sttt_wins)" }
   ]
  },
  {
   "title": "Games",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sttt_games_created)" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{name=\"sttt\"})"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 26, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{namespace=\"sttt\"}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sttt_players_joined) " }
   ]
  },
  {
   "title": "HTTP Calls",
   "type": "graph",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(sttt_http_calls)" }
   ]
  }
 ]
}